# Hugo ç«™ç‚¹åŸºç¡€é…ç½®
baseURL = "https://zisai.com/"  # ç«™ç‚¹æ ¹ URLï¼Œç”¨äºç”Ÿæˆç»å¯¹é“¾æ¥
languageCode = "zh-cn"  # ç«™ç‚¹è¯­è¨€ï¼Œzh-cn è¡¨ç¤ºä¸­æ–‡ï¼ˆç®€ä½“ï¼‰
title = "ç´«å¡ zisai.com"  # ç«™ç‚¹æ ‡é¢˜ï¼Œæ˜¾ç¤ºåœ¨é¡µé¢æ ‡é¢˜å’Œå¯¼èˆªä¸­
theme = "PaperMod"  # ä½¿ç”¨çš„ä¸»é¢˜åç§°

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true

  [params.profileMode]
    enabled = true
    title = "ç´«å¡" # å¯é€‰ï¼Œé»˜è®¤ä½¿ç”¨ç«™ç‚¹æ ‡é¢˜
    subtitle = "å¿ äºæŠ€æœ¯ï¼Œè¿½å¯»ç†æƒ³" # å¯é€‰ï¼Œé»˜è®¤ä½¿ç”¨ç«™ç‚¹å‰¯æ ‡é¢˜
    description = "è®°å½•æŠ€æœ¯ä¸æ€è€ƒçš„è§’è½" # å¯é€‰ï¼Œé»˜è®¤ä½¿ç”¨ç«™ç‚¹æè¿°
    imageUrl = "/images/shennan.jpg" # æ›¿æ¢ä¸ºä½ çš„å›¾ç‰‡è·¯å¾„
    imageTitle = "SHENNAN"
    imageWidth = 120
    imageHeight = 120
    [[params.profileMode.buttons]]
      name = "æ–‡ç« å½’æ¡£"
      url = "/archive"
    [[params.profileMode.buttons]]
      name = "GitHub"
      url = "https://github.com/mythflair"

    [[params.socialIcons]]
      name = "email"
      url = "mailto:mythflair@hotmail.com"
    [[params.socialIcons]]
      name = "GitHub"
      url = "https://github.com/mythflair"

    [[menu.main]]
      identifier = "posts"
      name = "ğŸ“ æ–‡ç« "
      url = "/posts/"
      weight = 10
    [[menu.main]]
     identifier = "story"
     name = "ğŸ—‚ï¸ æ•…äº‹"
     url = "/story/"
     weight = 20
    [[menu.main]]
      identifier = "about"
      name = "â„¹ï¸ å…³äº"
      url = "/about/"
      weight = 30
[outputs]
  home = ["HTML", "RSS", "JSON"]